apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
  labels:
    app: shoppingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      containers:
        - name: shoppingapi
          image: mrdockerbabe/shoppingapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080   # Change container port to 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: connection_string
            - name: ASPNETCORE_HTTP_PORTS  # Added to explicitly set the listening port
              value: "8080"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
spec:
  type: NodePort
  selector:
    app: shoppingapi
  ports:
    - protocol: TCP
      port: 8000        # External port on which the service is exposed
      targetPort: 8080  # Port on the container to forward the traffic to
      nodePort: 31000   # NodePort to access the service
