name: Build and Push Docker Image for .NET Core 8 MVC (ShoppingApp)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers (optional)
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up .NET Core 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore Dependencies
        run: dotnet restore Shopping/Shopping.Client/Shopping.Client.csproj

      - name: Build Project
        run: dotnet build Shopping/Shopping.Client/Shopping.Client.csproj --configuration Release --output ./app/build

      - name: Publish the App
        run: dotnet publish Shopping/Shopping.Client/Shopping.Client.csproj --configuration Release --output ./app/publish /p:UseAppHost=false

      - name: Build Docker Image
        run: docker build -t mrdockerbabe/shoppingapp -f Shopping/Shopping.Client/Dockerfile .

      - name: Log in to Docker Hub (Skip for Public Repo)
        if: ${{ secrets.DOCKER_USERNAME }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push mrdockerbabe/shoppingapp:latest
